- Media:
    - Jellyfin:
        icon: jellyfin
        href: https://jellyfin.edvardsson.dev
        siteMonitor: https://jellyfin.edvardsson.dev
        description: The Free Software Media System
    - Jellyseerr:
        icon: jellyseerr
        href: https://jellyseerr.edvardsson.dev
        siteMonitor: https://jellyseerr.edvardsson.dev
        description: Media request and discovery manager for Jellyfin
    - Immich:
        icon: immich
        href: https://immich.edvardsson.dev
        siteMonitor: https://immich.edvardsson.dev
        description: Self-hosted photo and video management solution

- Arr:
    - Prowlarr:
        icon: prowlarr
        href: https://prowlarr.edvardsson.dev
        siteMonitor: https://prowlarr.edvardsson.dev
        description: PVR indexer
    - Radarr:
        icon: radarr
        href: https://radarr.edvardsson.dev
        siteMonitor: https://radarr.edvardsson.dev
        description: Movie collection manager
    - Sonarr:
        icon: sonarr
        href: https://sonarr.edvardsson.dev
        siteMonitor: https://sonarr.edvardsson.dev
        description: TV show collection manager
    - Bazarr:
        icon: bazarr
        href: https://bazarr.edvardsson.dev
        siteMonitor: https://bazarr.edvardsson.dev
        description: Subtitle manager
    - Deluge:
        icon: deluge
        href: https://deluge.edvardsson.dev
        siteMonitor: https://deluge.edvardsson.dev
        description: Torrent client

- Services:
    - Grafana:
        icon: grafana
        href: https://grafana.edvardsson.dev
        siteMonitor: https://grafana.edvardsson.dev
        description: Dashboarding tool
    - Prometheus:
        icon: prometheus
        href: https://prometheus.edvardsson.dev
        siteMonitor: https://prometheus.edvardsson.dev
        description: Event monitoring and alerting
    - Healthchecks:
        icon: healthchecks
        href: https://healthchecks.edvardsson.dev
        siteMonitor: https://healthchecks.edvardsson.dev
        description: Cron job monitoring

- External:
    - Unraid:
        icon: unraid
        href: https://unraid.edvardsson.dev
        siteMonitor: https://unraid.edvardsson.dev
        description: Unraid host UI
    - Dockge:
        icon: mdi-docker
        href: https://dockge.edvardsson.dev
        siteMonitor: https://dockge.edvardsson.dev
        description: Docker Compose stack manager
    - UniFi:
        icon: unifi
        href: https://unifi
        siteMonitor: https://unifi
        description: UniFi controller
    - Ugreen:
        icon: ugreen-nas
        href: https://ugreen.{{HOMEPAGE_VAR_TAILNET_DOMAIN}}
        siteMonitor: https://ugreen.{{HOMEPAGE_VAR_TAILNET_DOMAIN}}
        description: Ugreen NAS
    - Ugreen - Backrest:
        icon: backrest
        href: http://ugreen.{{HOMEPAGE_VAR_TAILNET_DOMAIN}}:9898
        siteMonitor: http://ugreen.{{HOMEPAGE_VAR_TAILNET_DOMAIN}}:9898
        description: Ugreen Backrest
    - Tower - Backrest:
        icon: backrest
        href: http://tower:9898
        siteMonitor: http://tower:9898
        description: Tower Backrest
