title: Homelab
headerStyle: clean
statusStyle: dot
hideVersion: true
maxGroupColumns: 4
layout:
  Core:
    header: true
    style: column
  Media & Downloads:
    header: true
    style: column
  Monitoring & Ops:
    header: true
    style: column
  Utilities & External:
    header: true
    style: column
