apiVersion: 1

contactPoints:
  - orgId: 1
    name: booli-discord
    receivers:
      - uid: booli_discord
        type: discord
        disableResolveMessage: false
        settings:
          url: $GRAFANA_DISCORD_WEBHOOK
          avatar_url: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/grafana.png
          use_discord_username: false
          message: |
            {{ template "default.message" . }}
