services:
  caddy:
    container_name: caddy
    user: 1000:1000
    build:
      context: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config:/etc/caddy # Allows for automatic config reload https://github.com/caddyserver/caddy/issues/5735#issuecomment-1675896585
      - ../../data/caddy/data:/data
      - ../../data/caddy/caddy_config:/config
    environment:
      CF_ZONE_TOKEN: ${CF_ZONE_TOKEN}
      CF_API_TOKEN: ${CF_API_TOKEN}
    networks:
      dmz:
      caddy_internal:


networks:
  dmz:
    name: dmz
    driver: bridge
  caddy_internal:
    name: caddy_internal
    driver: bridge
    internal: true
