services:
  caddy:
    container_name: caddy
    user: "${PUID}:${PGID}"
    build:
      context: .
    restart: unless-stopped
    dns:
      - 100.100.100.100
      - 10.0.0.1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config:/etc/caddy # Allows for automatic config reload https://github.com/caddyserver/caddy/issues/5735#issuecomment-1675896585
      - ${APPDATA_ROOT}/caddy/data:/data
      - ${APPDATA_ROOT}/caddy/config:/config
      - ${APPDATA_ROOT}/caddy/logs:/var/log/caddy
    environment:
      ACME_EMAIL: ${ACME_EMAIL}
      BASE_DOMAIN: ${BASE_DOMAIN}
      TAILNET_DOMAIN: ${TAILNET_DOMAIN}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/caddy.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "sh"
      folder.view3: "caddy"
    networks:
      dmz:
      caddy_internal:

networks:
  dmz:
    name: dmz
    driver: bridge
  caddy_internal:
    name: caddy_internal
    driver: bridge
    internal: true
