name: homepage

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    dns:
      - ${DOCKER_DNS_1}
      - ${DOCKER_DNS_2}
      - ${DOCKER_DNS_3}
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      HOMEPAGE_ALLOWED_HOSTS: homepage.${BASE_DOMAIN}
    volumes:
      - ./config:/app/config
      - ${APPDATA_ROOT}/homepage/logs:/app/config/logs
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homepage.png"
      net.unraid.docker.webui: "https://homepage.edvardsson.dev"
      net.unraid.docker.shell: "sh"
      folder.view3: "homepage"
    networks:
      - caddy_internal
      - default

networks:
  caddy_internal:
    external: true
