name: homepage

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    dns:
      - 100.100.100.100
      - 10.0.0.1
    env_file:
      - .env
    ports:
      - "${HOMEPAGE_PUBLISHED_PORT}:3000"
    environment:
      TZ: ${TZ}
      HOMEPAGE_ALLOWED_HOSTS: homepage.${BASE_DOMAIN}
    volumes:
      - ./config:/app/config
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homepage.png"
      net.unraid.docker.webui: "https://homepage.edvardsson.dev"
      net.unraid.docker.shell: "sh"
      folder.view: "homepage"
    networks:
      - caddy_internal
      - default

networks:
  caddy_internal:
    external: true
