name: deluge-vpn

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      VPN_TYPE: ${VPN_TYPE}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY}
      WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP}
      WIREGUARD_ENDPOINT_PORT: ${WIREGUARD_ENDPOINT_PORT}
      WIREGUARD_PRESHARED_KEY: ${WIREGUARD_PRESHARED_KEY}
      DNS_ADDRESS: ${VPN_DNS_ADDRESS}
      FIREWALL_INPUT_PORTS: 8112,58846
      FIREWALL_OUTBOUND_SUBNETS: 10.0.0.0/24
    ports:
      - "${DELUGE_WEB_PUBLISHED_PORT}:8112"
      - "58846:58846"
    networks:
      - caddy_internal

  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    env_file:
      - .env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DELUGE_LOGLEVEL: info
      DELUGE_WEBUI_PASSWORD: ${DELUGE_PASSWORD}
    volumes:
      - ${APPDATA_ROOT}/deluge:/config
      - ${DOWNLOADS_ROOT}:/downloads

networks:
  caddy_internal:
    external: true
