services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA_ROOT}/dockge:/app/data
      - /mnt/user/appdata/homelab/docker:/mnt/user/appdata/homelab/docker
    environment:
      DOCKGE_STACKS_DIR: /mnt/user/appdata/homelab/docker
